import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[window]
opacity = 0.7

[font]
size = 10.0

[font.bold]
family = "Cousine Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Cousine Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Cousine Nerd Font"
style = "Italic"

[font.normal]
family = "Cousine Nerd Font"
style = "Regular"
